<?php

namespace Cac\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedRepository extends EntityRepository
{
}
