# Cac/BarBundle/Resources/config/routing.yml

# user_one_registration:
#     pattern:  /register/user-one
#     defaults: { _controller: AcmeUserBundle:RegistrationUserOne:register }

# user_two_registration:
#     pattern:  /register/user-two
#     defaults: { _controller: AcmeUserBundle:RegistrationUserTwo:register }