<?php

namespace Cac\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasicUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasicUserRepository extends EntityRepository
{
    public function research($string)
    {
        setlocale(LC_TIME, "fr_FR");
        $today = ucfirst(strftime("%A"));

        $query = $this->createQueryBuilder('bu')
            ->select('bu.id, bu.name, bu.firstname, u, p')
            ->leftJoin(
                'Cac\UserBundle\Entity\User',
                'u',
                \Doctrine\ORM\Query\Expr\Join::WITH,
                'bu.id = u.id'
            )
            ->leftJoin('u.PromoOffertes', 'p')
            ->where('bu.name LIKE :name')
            ->orWhere('bu.firstname LIKE :firstname')
            ->orWhere('p.reference LIKE :reference')
            ->setParameters(array('name' => '%'.$string.'%', 'firstname' => '%'.$string.'%', 'reference' => '%'.$string.'%'));
        
        $result = $query->getQuery()
                        ->getArrayResult();
        return $result;
    }
}
