<?php

namespace Cac\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BigbossRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BigbossRepository extends EntityRepository
{
}
