cac_admin:
    resource: "@CacAdminBundle/Controller/"
    type:     annotation
    prefix:   /

cac_bar:
    resource: "@CacBarBundle/Controller/"
    type:     annotation
    prefix:   /

cac_user:
    resource: "@CacUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"