cac_navigation:
    resource: "@CacNavigationBundle/Controller/"
    type:     annotation
    prefix:   /

cac_mailing:
    resource: "@CacMailingBundle/Controller/"
    type:     annotation
    prefix:   /

cac_payment:
    resource: "@CacPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

cac_admin:
    resource: "@CacAdminBundle/Controller/"
    type:     annotation
    prefix:   /

cac_bar:
    resource: "@CacBarBundle/Controller/"
    type:     annotation
    prefix:   /

cac_user:
    resource: "@CacUserBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

facebook_login:
    pattern: /login/check-facebook
