cac_navigation:
    resource: "@CacNavigationBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
  prefix: /oauth-login

cac_mailing:
    resource: "@CacMailingBundle/Controller/"
    type:     annotation
    prefix:   /

cac_payment:
    resource: "@CacPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

cac_admin:
    resource: "@CacAdminBundle/Controller/"
    type:     annotation
    prefix:   /

cac_bar:
    resource: "@CacBarBundle/Controller/"
    type:     annotation
    prefix:   /

cac_user:
    resource: "@CacUserBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

facebook_login:
    pattern: /login/check-facebook
