security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_BARMAN:       ROLE_USER
        ROLE_BIGBOSS:      ROLE_BARMAN
        ROLE_ADMIN:       [ROLE_BIGBOSS, ROLE_USER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     home
                domain:   ~
            context: user
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer:        true
            logout:       true
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bigboss/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/avis/, role: ROLE_USER }
        - { path: ^/bars/edit, role: ROLE_BARMAN }
        - { path: ^/pro/, role: ROLE_BARMAN }
        - { path: ^/bars/new, role: ROLE_BIGBOSS }
        - { path: ^/pro/new, role: ROLE_BIGBOSS }
        - { path: ^/bigboss/, role: ROLE_BIGBOSS }
        - { path: ^/barman/register, role: ROLE_BIGBOSS }
        - { path: ^/whostheboss/, role: ROLE_ADMIN }
