<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarRepository extends EntityRepository
{
	public function getSearchResult($value)
	{
		return $this->getEntityManager()
	            ->createQuery('SELECT b FROM CacBarBundle:Bar b Where b.name LIKE :Value')
	            ->setParameters(array('Value' => $value))
	            ->getResult();
	}
}
