<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarRepository extends EntityRepository
{
	public function getBarByAuthorId($id) {
	    $qb=$this->createQueryBuilder('m');
	    $qb->from('CacBarBundle:Bar', 'b')
	    ->where('b.author = :id')                
	    ->setParameter('id', $id)
	    ->getQuery()->getResult();
		return $qb;
	}
}
