<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarRepository extends EntityRepository
{
	public function getSearchResult($value)
	{
		return $this->getEntityManager()
	            ->createQuery('SELECT b FROM CacBarBundle:Bar b Where b.name LIKE :Value')
	            ->setParameters(array('Value' => $value))
	            ->getResult();
	}

	public function findOneRandom(){
	   $max=$this->getMaxId();
	   return $this->getEntityManager()
	     ->createQuery('SELECT b.id FROM CacBarBundle:Bar b WHERE b.id >= :rand')
	     ->setParameter('rand',rand(0,$max))
	     ->setMaxResults(1)
	     ->getSingleResult();
	}
 
	private function getMaxId(){
	   return $this->getEntityManager()
	      ->createQuery('SELECT MAX(b.id) FROM CacBarBundle:Bar b')
	      ->getSingleScalarResult();
	}

	public function research($string)
	{
		// Mac et UNIX/Linux
        setlocale(LC_TIME, "fr_FR");
        // Windows
        //setlocale(LC_TIME, "french");
        $today = ucfirst(strftime("%A"));

		$query = $this->createQueryBuilder('b')
            ->select('b, p, o, c')
            ->leftJoin('b.promotions', 'p')
            ->leftJoin('p.options', 'o')
            ->leftJoin('b.comments', 'c')
            ->where('b.name LIKE :name OR b.adress LIKE :adress OR b.zipcode LIKE :zipcode OR b.town LIKE :town')
            ->andWhere('p.day = :today')
            ->andWhere('o.categoryShortcode = :value')
            ->setParameters(array('name' => '%'.$string.'%', 'adress' => '%'.$string.'%', 'zipcode' => '%'.$string.'%', 'town' => '%'.$string.'%', 'today' => $today, 'value' => 'value'));
        
        $result = $query->getQuery()
                        ->getArrayResult();
        return $result;
	}
}
