<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DayScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayScheduleRepository extends EntityRepository
{
	public function checkClosedDays($dayName, $id)
	{
		$query = $this->createQueryBuilder('d')
			->select('d.status')
			->where('d.bar = :barId')
			->andWhere('d.dayName = :dayName')
			->setParameters(array('barId' => $id, 'dayName' => $dayName));

		$result = $query->getQuery()
			->getSingleScalarResult();
		return $result;
	}
}
