<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HighlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HighlightRepository extends EntityRepository
{
}
