<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionRepository extends EntityRepository
{
}
