<?php

namespace Cac\BarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SponsorshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorshipRepository extends EntityRepository
{
	public function checkAvailableDay($fDate, $id)
	{
		$query = $this->createQueryBuilder('s')
            ->select('COUNT(s.id)')
            ->where('s.bar = :barId')
            ->andWhere('SUBSTRING(s.usedAt, 1, 10) = :fDate')
            ->setParameters(array('barId' => $id, 'fDate' => $fDate));
        
        $result = $query->getQuery()
                        ->getSingleScalarResult();
        return $result;
	}
}
